StockHavenBundle\Entity\items_stocks:
    type: entity
    table: null
    repositoryClass: StockHavenBundle\Repository\items_stocksRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
    manyToOne:
        itemId:
            targetEntity: item
            inversedBy: itemsStocks
            joinColumn:
                name: item_id
                referencedColumnName: id
        stockId:
            targetEntity: stock
            inversedBy: itemsStocks
            joinColumn:
                name: stock_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
