StockHavenBundle\Entity\saveOperation:
    type: entity
    table: null
    repositoryClass: StockHavenBundle\Repository\saveOperationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        modificationDate:
            type: datetimetz
            nullable: true
            column: modification_date
        element_name:
            type: string
            column: element_name
        type_element:
            type: string
            column: type_element
    manyToOne:
        operationId:
            targetEntity: operation
            joinColumn:
                name: operation_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
