StockHavenBundle\Entity\unit:
    type: entity
    table: null
    repositoryClass: StockHavenBundle\Entity\unitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        longName:
            type: string
            length: 255
            column: long_name
        shortName:
            type: string
            length: 255
            column: short_name
    lifecycleCallbacks: {  }
