<?php

namespace StockHavenBundle\Repository;

/**
 * items_stocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class items_stocksRepository extends \Doctrine\ORM\EntityRepository
{
}
