<?php

namespace StockHavenBundle\Repository;

/**
 * itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemRepository extends \Doctrine\ORM\EntityRepository
{
    public function statItem ()
    {
        $con = $this->getEntityManager()->getConnection();
        $q = $con->prepare("SELECT count(*) as nb,type.name as name FROM item JOIN type on type.id = item.type_id group by type.id");
        $q->execute();
        $result = $q->fetchAll();
        return $result;
        //$query = $this->_em->createQuery();
    }
}
