<?php

namespace StockHavenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * unitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unitRepository extends EntityRepository
{
}
