sh_site_part_dashboard:
    path:     /ajax/dashboard
    defaults: { _controller: StockHavenBundle:Site:dashboard }

sh_dashboard_add_super_user:
    path:     /ajax/dashboard/addSuperUser
    defaults: { _controller: StockHavenBundle:Site:AddSuperUser }

sh_dashboard_remove_super_user:
    path:     /ajax/dashboard/removeSuperUser
    defaults: { _controller: StockHavenBundle:Site:removeSuperUser }

sh_dev_axel:
    path:     /dev/axel/currency
    defaults: {_controller: StockHavenBundle:DevAxel:currency }

sh_site_part_project:
    path:     /ajax/projects/{slug}
    defaults: { _controller: StockHavenBundle:Site:projects, slug: 1 }

sh_search:
    path:     /ajax/search
    defaults: { _controller: StockHavenBundle:Site:search }

sh_connection:
    path:     /
    defaults: { _controller: StockHavenBundle:AuthConnect:Start }

sh_logout:
    path:     /logout
    defaults: { _controller: StockHavenBundle:AuthConnect:logout }

sh_register:
    path:     /register
    defaults: { _controller: StockHavenBundle:AuthConnect:Register }

sh_stock_add:
    path:     /ajax/stock/add
    defaults: { _controller: StockHavenBundle:AuthConnect:StockAdd }

sh_login:
    path:     /login_check
    defaults: { _controller: StockHavenBundle:AuthConnect:LoginCheck }
    methods: [POST]

sh_register_check:
    path:     /register_check
    defaults: { _controller: StockHavenBundle:AuthConnect:RegisterCheck }
    methods: [POST]

sh_stock_create:
    path:     /ajax/stock/create
    defaults: { _controller: StockHavenBundle:Stock:create }

sh_stock_delete:
    path:     /ajax/stock/delete
    defaults: { _controller: StockHavenBundle:Stock:delete }

sh_stock_add_user:
    path:     /ajax/stock/addUser
    defaults: { _controller: StockHavenBundle:Stock:addUser }

sh_stock_add_item:
    path:     /ajax/stock/addItem
    defaults: { _controller: StockHavenBundle:StockItem:addItem }

sh_stock_add_item_in_stock:
    path:     /ajax/stock/addItemInStock
    defaults: { _controller: StockHavenBundle:StockItem:addItemInStock }

sh_stock_remove_item_in_stock:
    path:     /ajax/stock/removeItemInStock
    defaults: { _controller: StockHavenBundle:StockItem:removeItemInStock }

sh_stock_remove_user:
    path:     /ajax/stock/removeUser
    defaults: {_controller: StockHavenBundle:Stock:removeUser }
sh_stock:
    path:     /ajax/stock
    defaults: { _controller: StockHavenBundle:Stock:stock }

sh_item_delete:
    path:     /ajax/item/delete
    defaults: { _controller: StockHavenBundle:Item:delete }

sh_item_create:
    path:     /ajax/item/create
    defaults: { _controller: StockHavenBundle:Item:create }

sh_item:
    path:     /ajax/item
    defaults: { _controller: StockHavenBundle:Item:item }

sh_store_create:
    path:     /ajax/store/create
    defaults: { _controller: StockHavenBundle:Store:create }

sh_store_delete:
    path:     /ajax/store/delete
    defaults: { _controller: StockHavenBundle:Store:delete }

sh_store:
    path:     /ajax/store
    defaults: { _controller: StockHavenBundle:Store:store}

sh_change_profile:
    path:     /ajax/profile
    defaults: { _controller:  StockHavenBundle:Site:profile }

sh_type_create:
    path:     /ajax/type/create
    defaults: { _controller:  StockHavenBundle:Type:create }

sh_type_delete:
    path:     /ajax/type/delete
    defaults: { _controller: StockHavenBundle:Type:delete }

sh_type:
    path:     /ajax/type
    defaults: { _controller: StockHavenBundle:Type:type }










sh_site_part_deny_all_not_found:
    path:     /ajax/{path}
    defaults: { _controller: StockHavenBundle:Site:error_404_other_ajax }
    requirements:
