#
# Site principal
#

sh_site_part_dashboard:
    path:     /ajax/dashboard
    defaults: { _controller: StockHavenBundle:Site:dashboard }

sh_dashboard_add_super_user:
    path:     /ajax/dashboard/addSuperUser
    defaults: { _controller: StockHavenBundle:Site:AddSuperUser }

sh_dashboard_remove_super_user:
    path:     /ajax/dashboard/removeSuperUser
    defaults: { _controller: StockHavenBundle:Site:removeSuperUser }

sh_search:
    path:     /ajax/search
    defaults: { _controller: StockHavenBundle:Site:search }

#
# Création d'élément dans la db
#

sh_dev_axel2:
    path:     /dev/axel/country
    defaults: { _controller: StockHavenBundle:DevAxel:country }

sh_dev_axel:
    path:     /dev/axel/currency
    defaults: {_controller: StockHavenBundle:DevAxel:currency }

#
# affichage du projet
#

sh_site_part_project:
    path:     /ajax/projects/{slug}
    defaults: { _controller: StockHavenBundle:Site:projects, slug: 1 }

#
# cooonection , déconnection, enregistrement
#

sh_connection:
    path:     /
    defaults: { _controller: StockHavenBundle:AuthConnect:Start }

sh_logout:
    path:     /logout
    defaults: { _controller: StockHavenBundle:AuthConnect:logout }

sh_register:
    path:     /register
    defaults: { _controller: StockHavenBundle:AuthConnect:Register }

sh_login:
    path:     /login_check
    defaults: { _controller: StockHavenBundle:AuthConnect:LoginCheck }
    methods: [POST]

sh_register_check:
    path:     /register_check
    defaults: { _controller: StockHavenBundle:AuthConnect:RegisterCheck }
    methods: [POST]

#
# Gestion de stock
#

sh_stock_add:
    path:     /ajax/stock/add
    defaults: { _controller: StockHavenBundle:AuthConnect:StockAdd }

sh_stock_edit_view:
    path:     /ajax/stock/editView
    defaults: { _controller: StockHavenBundle:Stock:editView }

sh_stock_edit:
    path:     /ajax/stock/edit
    defaults: { _controller: StockHavenBundle:Stock:edit }

sh_stock_create:
    path:     /ajax/stock/create
    defaults: { _controller: StockHavenBundle:Stock:create }

sh_stock_delete:
    path:     /ajax/stock/delete
    defaults: { _controller: StockHavenBundle:Stock:delete }

sh_stock_add_user:
    path:     /ajax/stock/addUser
    defaults: { _controller: StockHavenBundle:Stock:addUser }

sh_stock_remove_user:
    path:     /ajax/stock/removeUser
    defaults: {_controller: StockHavenBundle:Stock:removeUser }
sh_stock:
    path:     /ajax/stock
    defaults: { _controller: StockHavenBundle:Stock:stock }

#
# Gestion des views item_stock et stock_item
#

sh_stock_add_item:
    path:     /ajax/stock/addItem
    defaults: { _controller: StockHavenBundle:StockItem:addItem }

sh_stock_add_item_in_stock:
    path:     /ajax/stock/addItemInStock
    defaults: { _controller: StockHavenBundle:StockItem:addItemInStock }

sh_stock_add_stock_in_item:
    path:     /ajax/stock/addStockInItem
    defaults: { _controller:  StockHavenBundle:StockItem:addStockInItem }

sh_stock_remove_stock_in_item:
    path:     /ajax/stock/removeItemInStock
    defaults: { _controller: StockHavenBundle:StockItem:removeStockInItems }

sh_stock_remove_item_in_stock:
    path:     /ajax/stock/removeItemInStock
    defaults: { _controller: StockHavenBundle:StockItem:removeItemInStock }

sh_item_add_stock:
    path:     /ajax/stock/addStock
    defaults: { _controller: StockHavenBundle:StockItem:addStock }
#
# Gestion d'item
#

sh_item_edit_view:
    path:     /ajax/item/editView
    defaults: { _controller: StockHavenBundle:Item:editView }

sh_item_edit:
    path:     /ajax/item/edit
    defaults: { _controller: StockHavenBundle:Item:edit }

sh_item_delete:
    path:     /ajax/item/delete
    defaults: { _controller: StockHavenBundle:Item:delete }

sh_item_create:
    path:     /ajax/item/create
    defaults: { _controller: StockHavenBundle:Item:create }

sh_item:
    path:     /ajax/item
    defaults: { _controller: StockHavenBundle:Item:item }

#
# Gestion de store
#

sh_store_view_address:
    path:     /ajax/store/view/address
    defaults: { _controller: StockHavenBundle:Store:viewAddress }

sh_store_add_address:
    path:     /ajax/store/add/address
    defaults: { _controller: StockHavenBundle:Store:addAddress }

sh_store_view_one:
    path:     /ajax/store/view/one
    defaults: { _controller: StockHavenBundle:Store:selectStore }

sh_store_edit_view:
    path:     /ajax/store/edit/view
    defaults: { _controller: StockHavenBundle:Store:editView }

sh_store_edit:
    path:     /ajax/store/edit
    defaults: { _controller: StockHavenBundle:Store:edit }

sh_store_create:
    path:     /ajax/store/create
    defaults: { _controller: StockHavenBundle:Store:create }

sh_store_delete:
    path:     /ajax/store/delete
    defaults: { _controller: StockHavenBundle:Store:delete }

sh_store:
    path:     /ajax/store
    defaults: { _controller: StockHavenBundle:Store:store}

#
# Profile change
#

sh_change_profile:
    path:     /ajax/profile
    defaults: { _controller:  StockHavenBundle:Site:profile }

#
# Gestion de type
#

sh_type_edit_view:
    path:     /ajax/type/edit/view
    defaults: { _controller:  StockHavenBundle:Type:editView }

sh_type_edit:
    path:     /ajax/type/edit
    defaults: { _controller:  StockHavenBundle:Type:edit }

sh_type_create:
    path:     /ajax/type/create
    defaults: { _controller:  StockHavenBundle:Type:create }

sh_type_delete:
    path:     /ajax/type/delete
    defaults: { _controller: StockHavenBundle:Type:delete }

sh_type:
    path:     /ajax/type
    defaults: { _controller: StockHavenBundle:Type:type }









#
# page d'erreur par défaut
#

sh_site_part_deny_all_not_found:
    path:     /ajax/{path}
    defaults: { _controller: StockHavenBundle:Site:error_404_other_ajax }
    requirements:
